// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJbPzgyaa98sDmYoujVS-v5Nxj8b03ink',
    appId: '1:1016786265689:web:b078345a011b94e89c7348',
    messagingSenderId: '1016786265689',
    projectId: 'unitedareechola',
    authDomain: 'unitedareechola.firebaseapp.com',
    storageBucket: 'unitedareechola.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTBt2v8fNBKbNgbKj92lY_d_faInHalc',
    appId: '1:1016786265689:android:2cc6a6dc55c64dc19c7348',
    messagingSenderId: '1016786265689',
    projectId: 'unitedareechola',
    storageBucket: 'unitedareechola.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKIyiAWBeTMUGJfSlXe0oft9UARSF-AlU',
    appId: '1:1016786265689:ios:02b31e396aab5b669c7348',
    messagingSenderId: '1016786265689',
    projectId: 'unitedareechola',
    databaseURL: 'https://unitedareechola-default-rtdb.firebaseio.com',
    storageBucket: 'unitedareechola.appspot.com',
    androidClientId: '1016786265689-qd8qlua494ap05pdl71bnbglivff98pa.apps.googleusercontent.com',
    iosClientId: '1016786265689-71dkln8ckjirfr7es36jqp73588b8p2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitedAreechola',
  );

}